// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLpR9hUQrdIFhi1rnsgUnmS20GyvH46k',
    appId: '1:410685986181:web:369b37415cbde2ca9da0ec',
    messagingSenderId: '410685986181',
    projectId: 'task-71e07',
    authDomain: 'task-71e07.firebaseapp.com',
    storageBucket: 'task-71e07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8JICHUZDj76uLz76sMfGa5HQdx0BkcJ0',
    appId: '1:410685986181:android:3cc5b071bfaf58ce9da0ec',
    messagingSenderId: '410685986181',
    projectId: 'task-71e07',
    storageBucket: 'task-71e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBON71UCPnpifNyMfvWT-Z997iieTZm21I',
    appId: '1:410685986181:ios:a66e997b34bdda669da0ec',
    messagingSenderId: '410685986181',
    projectId: 'task-71e07',
    storageBucket: 'task-71e07.firebasestorage.app',
    iosBundleId: 'com.example.nawel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBON71UCPnpifNyMfvWT-Z997iieTZm21I',
    appId: '1:410685986181:ios:a66e997b34bdda669da0ec',
    messagingSenderId: '410685986181',
    projectId: 'task-71e07',
    storageBucket: 'task-71e07.firebasestorage.app',
    iosBundleId: 'com.example.nawel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALLpR9hUQrdIFhi1rnsgUnmS20GyvH46k',
    appId: '1:410685986181:web:b495b54714b15fea9da0ec',
    messagingSenderId: '410685986181',
    projectId: 'task-71e07',
    authDomain: 'task-71e07.firebaseapp.com',
    storageBucket: 'task-71e07.firebasestorage.app',
  );
}
